---
- hosts: all
  become: true
  gather_facts: True
  gather_subset: interfaces

  tasks:
    - name: "Pull latest tocen-live"
      shell: |
        docker pull {{ docker_image }}
    - name: "Stop and remove tocen-live containers"
      shell: |
        (docker stop tocen-live || true) && (docker rm tocen-live || true)

    - name: "Run container in detached mode"
      shell: |
          docker run -d \
          --name=tocen-live \
          -p 8077:8077 \
          -e TOCEN_API_KEY={{ tocen_api_key }} \
          -e REFRESH_INTERVAL="5 seconds" \
          --restart=always \
          --log-opt max-size=10m \
          --log-opt max-file=5 \
          {{ docker_image }}
